[package]
name = "connectivity-iroh"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
bytes.workspace = true
connectivity-api.workspace = true
futures-util.workspace = true
iroh.workspace = true
tokio.workspace = true
